version: "3"

services:
  app:
    build:
      context: .
    volumes:
      - "./:/var/www/app"
      - "~/.composer:/var/composer"
    environment:
      DATABASE_URL: "mysql://user:password@mysql:3306/database"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - "./docker/nginx:/etc/nginx/conf.d:ro"
      - ".:/var/www/app:ro"

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - "mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password

volumes:
  mysql: {}
