version: '2'

services:
    nginx:
        image: sf-nginx
        ports:
            - "80:80"

    php-fpm:
        image: sf-php-fpm

    mysql:
        image: mysql
        ports:
            - "3306:3306"
        volumes:
            - "mysql_data:/var/lib/mysql"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_USER: root
            MYSQL_DATABASE: database

volumes:
    mysql_data: {}
