version: "3"

services:
  app:
    build:
      context: .
    volumes:
      - "./:/var/www/app"
      - "~/.composer:/var/composer"
    environment:
      DATABASE_URL: "mysql://user:password@mysql:3306/database"
#      - BLACKFIRE_CLIENT_ID
#      - BLACKFIRE_CLIENT_TOKEN

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - "./docker/nginx:/etc/nginx/conf.d:ro"
      - ".:/var/www/app:ro"

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - "mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password

# Uncomment the following if you want to use blackfire agent.
# Don't forget to add the define the environment variables or to add them to your .env file.
#  blackfire:
#    image: blackfire/blackfire
#    environment:
#      - BLACKFIRE_SERVER_ID
#      - BLACKFIRE_SERVER_TOKEN
#      - BLACKFIRE_CLIENT_ID
#      - BLACKFIRE_CLIENT_TOKEN

volumes:
  mysql: {}
